 
spring.datasource.url=jdbc:sqlite:mundial2026.db
spring.datasource.driver-class-name=org.sqlite.JDBC
 
spring.jpa.properties.hibernate.dialect=org.hibernate.community.dialect.SQLiteDialect
spring.jpa.properties.hibernate.boot.allow_jdbc_metadata_access=false
 
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true